<?php
/**
 * Created by PhpStorm.
 * User: xuant
 * Date: 10/6/2018
 * Time: 10:17 PM
 */

namespace app\models;


use yii\base\Model;

class StepForm2 extends Model
{
    public $writer_level;
    public $customer_service;
    public function rules()
    {
        //return parent::rules(); // TODO: Change the autogenerated stub
        return[
            [['writer_level','customer_service'],'required'],
            //[['additional_materials'], 'file','skipOnEmpty' => false,'extensions' => 'docx',],
        ];
    }
}