<?php
/**
 * Created by PhpStorm.
 * User: xuant
 * Date: 10/2/2018
 * Time: 9:08 PM
 */

namespace app\models;
use Yii;
use yii\base\ErrorException;
use yii\base\Model;
use yii\db\Exception;
use yii\helpers\Inflector;
use app\models\Post;
use yii\web\UploadedFile;
use app\models\ServicePrice;


class UploadImage extends Model
{

    public $upload_file;

    public function rules()
    {
        //return parent::rules(); // TODO: Change the autogenerated stub
        $rules = [
            //[['upload_file'],'required'],
            [['upload_file'], 'safe'],
            [['upload_file'], 'file','extensions' => ['png','jpeg','jpg']],
         ];
         return array_merge(parent::rules(),$rules);
       /*return[
             [['type_of_service','type_of_paper','subject_area','topic','paper_details','academic_level','currency','writer_level','customer_service','method','upload_file',
                 'urgency'],'required', 'on' => self::SCENARIO_STEP1],
             ['id_writer','validateId'],
             [['upload_file'], 'file','extensions' => 'docx',],
             [['number_of_page','id_writer'],'integer'],
         ];*/
    }
    public function attributeLabels()
    {
        return [

        ];
    }

    public function UploadFile()
    {
        if ($this->upload_file) {
            $randomString = Yii::$app->getSecurity()->generateRandomString(20);
            $file = $randomString . '.' . $this->upload_file->extension;
            if (Yii::$app->user->identity->getImage()!= null)
            {
                if (file_exists(Yii::$app->basePath . '/web/' .'upload_img_user/'. Yii::$app->user->identity->getImage()))
                {
                    unlink(Yii::$app->basePath . '/web/' . 'upload_img_user/' . Yii::$app->user->identity->getImage());
                }
            }
            if ($this->upload_file->saveAs('upload_img_user/' . $file)) {
                $user = User::findIdentity(Yii::$app->user->getId());
                $user->Image = $file;
                if ($user->save()) {
                    return true;
                }
            } else {
                $this->addError('myFile', 'Unable to save the uploaded file');
            }
        }
        return false;
    }




}